"""
twin_sieve.py

Author: Youcef Hanniche
Date: 2025-05-03
Description:
    This module provides a sieve-based method to generate twin prime pairs
    using a mathematical approach based on the form 6k ± 1.
    
    Twin primes are prime pairs (p, p+2), and except for (3, 5), they must be of
    the form (6k - 1, 6k + 1). This sieve eliminates composite numbers
    generated by multiplying (6i ± 1)(6j ± 1), leaving behind only prime candidates.

Usage:
    from twin_sieve import twin_prime_sieve
    print(twin_prime_sieve(100))
"""

import math

def twin_primes(limit):
    """
    Generate all twin primes (p, p+2) such that p+2 <= limit.
    The algorithm uses a sieve based on the 6k ± 1 form.
    
    Parameters:
    -----------
    limit : int
        Upper bound of the search (inclusive).
    
    Yields:
    -------
    tuple of int
        Twin prime pair (p, p+2)
    """
    if limit < 5:
        return  # No twin primes possible

    # Calculate number of candidates of the form 6k ± 1 up to limit
    n = (limit + 1) // 6
    km1 = ((n + 1) // 5) + 1
    t = [0] * (n + 2 * km1)

    t[0] = 1  # mark 6*0-1 as non-candidate (out of range)

    # Sieve: mark non-twin-prime candidates
    for i in range(1, km1):
        km = ((n + 1) // ((6 * i) - 1)) + 1
        for j in range(i, km):
            for dx in [i + j, i - j, -i + j, -i - j]:
                idx = (6 * i * j) + dx
                if 0 <= idx < len(t):
                    t[idx] = 1

    # Yield valid twin primes from the sieve
    for i in range(1, n):
        if not t[i]:
            p1 = 6 * i - 1
            p2 = 6 * i + 1
            if p2 <= limit:
                yield (p1, p2)



if __name__ == "__main__":
    limit = 100
    twin_primes = twin_prime_sieve(limit)
    print(f"Twin primes up to {limit}:")
    print(twin_primes)
