"""
twin_sieve.py

Author: Youcef Hanniche
Date: 2025-05-03
Description:
    This module provides a sieve-based method to generate twin prime pairs
    using a mathematical approach based on the form 6k ± 1.
    
    Twin primes are prime pairs (p, p+2), and except for (3, 5), they must be of
    the form (6k - 1, 6k + 1). This sieve eliminates composite numbers
    generated by multiplying (6i ± 1)(6j ± 1), leaving behind only prime candidates.

Usage:
    from twin_sieve import twin_prime_sieve
    print(twin_prime_sieve(100))
"""

def twin_prime_sieve(limit: int) -> list[tuple[int, int]]:
    """
    Generate twin prime pairs up to a given limit using a sieve
    based on numbers of the form 6k ± 1.

    Twin primes are pairs of primes (p, p+2).
    This sieve filters out non-prime candidates by eliminating
    combinations generated from (6i ± 1)(6j ± 1) patterns.

    Parameters:
        limit (int): Upper bound of the search (inclusive).

    Returns:
        list[tuple[int, int]]: A list of twin prime pairs (p, p+2)
    """
    if limit < 5:
        return []

    n = (limit + 1) // 6
    km1 = ((n + 1) // 5) + 1  # upper bound for i in sieve
    t = [0] * (n + 2 * km1)   # sieve array

    t[0] = 1  # 0 is not a candidate

    for i in range(1, km1):
        km = ((n + 1) // ((6 * i) - 1)) + 1
        for j in range(i, km):
            for index in [
                (6 * i * j) + i + j,
                (6 * i * j) + i - j,
                (6 * i * j) - i + j,
                (6 * i * j) - i - j
            ]:
                if 0 <= index < len(t):
                    t[index] = 1

    # Collect twin prime pairs (6k - 1, 6k + 1)
    twins = []
    for i in range(1, n):
        if not t[i] and not t[i + 1]:
            p1 = 6 * i - 1
            p2 = 6 * i + 1
            if p2 <= limit:
                twins.append((p1, p2))

    return twins


if __name__ == "__main__":
    limit = 100
    twin_primes = twin_prime_sieve(limit)
    print(f"Twin primes up to {limit}:")
    print(twin_primes)
